import { styled } from '../stitches.config';

export const Card = styled('div', {
  // local resets here
  display: 'flex',
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems: 'center',
  flex: 1,
  fontSize: '$6',
  fontWeight: '$2',
  borderTopLeftRadius: '$3',
  borderTopRightRadius: '$3',

  variants: {
    variant: {
      blue: {
        $$scope3: '$colors$blue3',
        $$scope4: '$colors$blue4',
        $$scope5: '$colors$blue5',
        $$scope7: '$colors$blue7',
        $$scope8: '$colors$blue8',
        $$scope9: '$colors$blue9',
        $$scope10: '$colors$blue10',
        $$scope11: '$colors$blue11',
        $$scope12: '$colors$blue12',
        $$emphasis: '$colors$whiteA12',
      },
      sky: {
        $$scope3: '$colors$sky3',
        $$scope4: '$colors$sky4',
        $$scope5: '$colors$sky5',
        $$scope7: '$colors$sky7',
        $$scope8: '$colors$sky8',
        $$scope9: '$colors$sky9',
        $$scope10: '$colors$sky10',
        $$scope11: '$colors$sky11',
        $$scope12: '$colors$sky12',
        $$emphasis: '$colors$blackA12',
      },
      cyan: {
        $$scope3: '$colors$cyan3',
        $$scope4: '$colors$cyan4',
        $$scope5: '$colors$cyan5',
        $$scope7: '$colors$cyan7',
        $$scope8: '$colors$cyan8',
        $$scope9: '$colors$cyan9',
        $$scope10: '$colors$cyan10',
        $$scope11: '$colors$cyan11',
        $$scope12: '$colors$cyan12',
        $$emphasis: '$colors$whiteA12',
      },
      teal: {
        $$scope3: '$colors$teal3',
        $$scope4: '$colors$teal4',
        $$scope5: '$colors$teal5',
        $$scope7: '$colors$teal7',
        $$scope8: '$colors$teal8',
        $$scope9: '$colors$teal9',
        $$scope10: '$colors$teal10',
        $$scope11: '$colors$teal11',
        $$scope12: '$colors$teal12',
        $$emphasis: '$colors$whiteA12',
      },
      green: {
        $$scope3: '$colors$green3',
        $$scope4: '$colors$green4',
        $$scope5: '$colors$green5',
        $$scope7: '$colors$green7',
        $$scope8: '$colors$green8',
        $$scope9: '$colors$green9',
        $$scope10: '$colors$green10',
        $$scope11: '$colors$green11',
        $$scope12: '$colors$green12',
        $$emphasis: '$colors$whiteA12',
      },
      grass: {
        $$scope3: '$colors$grass3',
        $$scope4: '$colors$grass4',
        $$scope5: '$colors$grass5',
        $$scope7: '$colors$grass7',
        $$scope8: '$colors$grass8',
        $$scope9: '$colors$grass9',
        $$scope10: '$colors$grass10',
        $$scope11: '$colors$grass11',
        $$scope12: '$colors$grass12',
        $$emphasis: '$colors$whiteA12',
      },
      mint: {
        $$scope3: '$colors$mint3',
        $$scope4: '$colors$mint4',
        $$scope5: '$colors$mint5',
        $$scope7: '$colors$mint7',
        $$scope8: '$colors$mint8',
        $$scope9: '$colors$mint9',
        $$scope10: '$colors$mint10',
        $$scope11: '$colors$mint11',
        $$scope12: '$colors$mint12',
        $$emphasis: '$colors$blackA12',
      },
      yellow: {
        $$scope3: '$colors$yellow3',
        $$scope4: '$colors$yellow4',
        $$scope5: '$colors$yellow5',
        $$scope7: '$colors$yellow7',
        $$scope8: '$colors$yellow8',
        $$scope9: '$colors$yellow9',
        $$scope10: '$colors$yellow10',
        $$scope11: '$colors$yellow11',
        $$scope12: '$colors$yellow12',
        $$emphasis: '$colors$blackA12',
      },
      amber: {
        $$scope3: '$colors$amber3',
        $$scope4: '$colors$amber4',
        $$scope5: '$colors$amber5',
        $$scope7: '$colors$amber7',
        $$scope8: '$colors$amber8',
        $$scope9: '$colors$amber9',
        $$scope10: '$colors$amber10',
        $$scope11: '$colors$amber11',
        $$scope12: '$colors$amber12',
        $$emphasis: '$colors$blackA12',
      },
      red: {
        $$scope3: '$colors$red3',
        $$scope4: '$colors$red4',
        $$scope5: '$colors$red5',
        $$scope7: '$colors$red7',
        $$scope8: '$colors$red8',
        $$scope9: '$colors$red9',
        $$scope10: '$colors$red10',
        $$scope11: '$colors$red11',
        $$scope12: '$colors$red12',
        $$emphasis: '$colors$whiteA12',
      },
      tomato: {
        $$scope3: '$colors$tomato3',
        $$scope4: '$colors$tomato4',
        $$scope5: '$colors$tomato5',
        $$scope7: '$colors$tomato7',
        $$scope8: '$colors$tomato8',
        $$scope9: '$colors$tomato9',
        $$scope10: '$colors$tomato10',
        $$scope11: '$colors$tomato11',
        $$scope12: '$colors$tomato12',
        $$emphasis: '$colors$whiteA12',
      },
      crimson: {
        $$scope3: '$colors$crimson3',
        $$scope4: '$colors$crimson4',
        $$scope5: '$colors$crimson5',
        $$scope7: '$colors$crimson7',
        $$scope8: '$colors$crimson8',
        $$scope9: '$colors$crimson9',
        $$scope10: '$colors$crimson10',
        $$scope11: '$colors$crimson11',
        $$scope12: '$colors$crimson12',
        $$emphasis: '$colors$whiteA12',
      },
      orange: {
        $$scope3: '$colors$orange3',
        $$scope4: '$colors$orange4',
        $$scope5: '$colors$orange5',
        $$scope7: '$colors$orange7',
        $$scope8: '$colors$orange8',
        $$scope9: '$colors$orange9',
        $$scope10: '$colors$orange10',
        $$scope11: '$colors$orange11',
        $$scope12: '$colors$orange12',
        $$emphasis: '$colors$whiteA12',
      },
      brown: {
        $$scope3: '$colors$brown3',
        $$scope4: '$colors$brown4',
        $$scope5: '$colors$brown5',
        $$scope7: '$colors$brown7',
        $$scope8: '$colors$brown8',
        $$scope9: '$colors$brown9',
        $$scope10: '$colors$brown10',
        $$scope11: '$colors$brown11',
        $$scope12: '$colors$brown12',
        $$emphasis: '$colors$whiteA12',
      },
      purple: {
        $$scope3: '$colors$purple3',
        $$scope4: '$colors$purple4',
        $$scope5: '$colors$purple5',
        $$scope7: '$colors$purple7',
        $$scope8: '$colors$purple8',
        $$scope9: '$colors$purple9',
        $$scope10: '$colors$purple10',
        $$scope11: '$colors$purple11',
        $$scope12: '$colors$purple12',
        $$emphasis: '$colors$whiteA12',
      },
      plum: {
        $$scope3: '$colors$plum3',
        $$scope4: '$colors$plum4',
        $$scope5: '$colors$plum5',
        $$scope7: '$colors$plum7',
        $$scope8: '$colors$plum8',
        $$scope9: '$colors$plum9',
        $$scope10: '$colors$plum10',
        $$scope11: '$colors$plum11',
        $$scope12: '$colors$plum12',
        $$emphasis: '$colors$whiteA12',
      },
      violet: {
        $$scope3: '$colors$violet3',
        $$scope4: '$colors$violet4',
        $$scope5: '$colors$violet5',
        $$scope7: '$colors$violet7',
        $$scope8: '$colors$violet8',
        $$scope9: '$colors$violet9',
        $$scope10: '$colors$violet10',
        $$scope11: '$colors$violet11',
        $$scope12: '$colors$violet12',
        $$emphasis: '$colors$whiteA12',
      },
      pink: {
        $$scope3: '$colors$pink3',
        $$scope4: '$colors$pink4',
        $$scope5: '$colors$pink5',
        $$scope7: '$colors$pink7',
        $$scope8: '$colors$pink8',
        $$scope9: '$colors$pink9',
        $$scope10: '$colors$pink10',
        $$scope11: '$colors$pink11',
        $$scope12: '$colors$pink12',
        $$emphasis: '$colors$whiteA12',
      },
      indigo: {
        $$scope3: '$colors$indigo3',
        $$scope4: '$colors$indigo4',
        $$scope5: '$colors$indigo5',
        $$scope7: '$colors$indigo7',
        $$scope8: '$colors$indigo8',
        $$scope9: '$colors$indigo9',
        $$scope10: '$colors$indigo10',
        $$scope11: '$colors$indigo11',
        $$scope12: '$colors$indigo12',
        $$emphasis: '$colors$whiteA12',
      },
      lime: {
        $$scope3: '$colors$lime3',
        $$scope4: '$colors$lime4',
        $$scope5: '$colors$lime5',
        $$scope7: '$colors$lime7',
        $$scope8: '$colors$lime8',
        $$scope9: '$colors$lime9',
        $$scope10: '$colors$lime10',
        $$scope11: '$colors$lime11',
        $$scope12: '$colors$lime12',
        $$emphasis: '$colors$blackA12',
      },
      gray: {
        $$scope3: '$colors$gray3',
        $$scope4: '$colors$gray4',
        $$scope5: '$colors$gray5',
        $$scope7: '$colors$gray7',
        $$scope8: '$colors$gray8',
        $$scope9: '$colors$gray9',
        $$scope10: '$colors$gray10',
        $$scope11: '$colors$gray11',
        $$scope12: '$colors$gray12',
        $$emphasis: '$colors$whiteA12',
      },
      mauve: {
        $$scope3: '$colors$mauve3',
        $$scope4: '$colors$mauve4',
        $$scope5: '$colors$mauve5',
        $$scope7: '$colors$mauve7',
        $$scope8: '$colors$mauve8',
        $$scope9: '$colors$mauve9',
        $$scope10: '$colors$mauve10',
        $$scope11: '$colors$mauve11',
        $$scope12: '$colors$mauve12',
        $$emphasis: '$colors$whiteA12',
      },
      slate: {
        $$scope3: '$colors$slate3',
        $$scope4: '$colors$slate4',
        $$scope5: '$colors$slate5',
        $$scope7: '$colors$slate7',
        $$scope8: '$colors$slate8',
        $$scope9: '$colors$slate9',
        $$scope10: '$colors$slate10',
        $$scope11: '$colors$slate11',
        $$scope12: '$colors$slate12',
        $$emphasis: '$colors$whiteA12',
      },
      sage: {
        $$scope3: '$colors$sage3',
        $$scope4: '$colors$sage4',
        $$scope5: '$colors$sage5',
        $$scope7: '$colors$sage7',
        $$scope8: '$colors$sage8',
        $$scope9: '$colors$sage9',
        $$scope10: '$colors$sage10',
        $$scope11: '$colors$sage11',
        $$scope12: '$colors$sage12',
        $$emphasis: '$colors$whiteA12',
      },
      sand: {
        $$scope3: '$colors$sand3',
        $$scope4: '$colors$sand4',
        $$scope5: '$colors$sand5',
        $$scope7: '$colors$sand7',
        $$scope8: '$colors$sand8',
        $$scope9: '$colors$sand9',
        $$scope10: '$colors$sand10',
        $$scope11: '$colors$sand11',
        $$scope12: '$colors$sand12',
        $$emphasis: '$colors$whiteA12',
      },
      olive: {
        $$scope3: '$colors$olive3',
        $$scope4: '$colors$olive4',
        $$scope5: '$colors$olive5',
        $$scope7: '$colors$olive7',
        $$scope8: '$colors$olive8',
        $$scope9: '$colors$olive9',
        $$scope10: '$colors$olive10',
        $$scope11: '$colors$olive11',
        $$scope12: '$colors$olive12',
        $$emphasis: '$colors$whiteA12',
      },
    },
    type: {
      1: {
        bg: 'inherit',
        border: '1px solid $$scope7',
        color: '$$scope11',
        '&:hover': {
          border: '1px solid $$scope8',
        },
      },
      2: {
        bg: '$$scope3',
        border: '1px solid $$scope7',
        color: '$$scope11',
        '&:hover': {
          bg: '$$scope4',
          border: '1px solid $$scope8',
        },
        '&:active': {
          bg: '$$scope5',
        },
      },
      3: {
        bg: '$$scope3',
        border: '1px solid $$scope7',
        color: '$$scope12',
        '&:hover': {
          bg: '$$scope4',
          border: '1px solid $$scope8',
        },
        '&:active': {
          bg: '$$scope5',
        },
      },
      4: {
        bg: '$$scope9',
        border: '1px solid $$scope9',
        color: '$$emphasis',
        '&:hover': {
          bg: '$$scope10',
          border: '1px solid $$scope10',
        },
      },
    },
  },
  defaultVariants: {
    variant: 'blue',
    type: 4,
  },
});
