import { createStitches } from '@stitches/react';
import type * as Stitches from '@stitches/react';
import * as Radix from '@radix-ui/colors';
import { SCREENS } from './constants';

export const {
  styled,
  config,
  theme,
  createTheme,
  globalCss,
  keyframes,
} = createStitches({
  theme: {
    colors: {
      ...Radix.gray,
      ...Radix.mauve,
      ...Radix.slate,
      ...Radix.sage,
      ...Radix.olive,
      ...Radix.sand,
      ...Radix.tomato,
      ...Radix.red,
      ...Radix.crimson,
      ...Radix.pink,
      ...Radix.plum,
      ...Radix.purple,
      ...Radix.violet,
      ...Radix.indigo,
      ...Radix.blue,
      ...Radix.cyan,
      ...Radix.teal,
      ...Radix.green,
      ...Radix.grass,
      ...Radix.orange,
      ...Radix.brown,
      // use dark text on these
      ...Radix.sky,
      ...Radix.mint,
      ...Radix.lime,
      ...Radix.yellow,
      ...Radix.amber,
      // has opacity
      ...Radix.blackA,
      ...Radix.whiteA,

      bg1: '$slate1',
      bg2: '$slate2',
      bg3: '$slate3',
      bg4: '$slate4',
      bg5: '$slate5',
      bg6: '$slate6',
      bg7: '$slate7',
      bg8: '$slate8',
      bg9: '$slate9',
      bg10: '$slate10',
      bg11: '$slate11',
      bg12: '$slate12',

      primary1: '$blue1',
      primary2: '$blue2',
      primary3: '$blue3',
      primary4: '$blue4',
      primary5: '$blue5',
      primary6: '$blue6',
      primary7: '$blue7',
      primary8: '$blue8',
      primary9: '$blue9',
      primary10: '$blue10',
      primary11: '$blue11',
      primary12: '$blue12',

      secondary1: '$pink1',
      secondary2: '$pink2',
      secondary3: '$pink3',
      secondary4: '$pink4',
      secondary5: '$pink5',
      secondary6: '$pink6',
      secondary7: '$pink7',
      secondary8: '$pink8',
      secondary9: '$pink9',
      secondary10: '$pink10',
      secondary11: '$pink11',
      secondary12: '$pink12',

      accent1: '$violet1',
      accent2: '$violet2',
      accent3: '$violet3',
      accent4: '$violet4',
      accent5: '$violet5',
      accent6: '$violet6',
      accent7: '$violet7',
      accent8: '$violet8',
      accent9: '$violet9',
      accent10: '$violet10',
      accent11: '$violet11',
      accent12: '$violet12',

      error1: '$red1',
      error2: '$red2',
      error3: '$red3',
      error4: '$red4',
      error5: '$red5',
      error6: '$red6',
      error7: '$red7',
      error8: '$red8',
      error9: '$red9',
      error10: '$red10',
      error11: '$red11',
      error12: '$red12',

      warning1: '$yellow1',
      warning2: '$yellow2',
      warning3: '$yellow3',
      warning4: '$yellow4',
      warning5: '$yellow5',
      warning6: '$yellow6',
      warning7: '$yellow7',
      warning8: '$yellow8',
      warning9: '$yellow9',
      warning10: '$yellow10',
      warning11: '$yellow11',
      warning12: '$yellow12',

      success1: '$green1',
      success2: '$green2',
      success3: '$green3',
      success4: '$green4',
      success5: '$green5',
      success6: '$green6',
      success7: '$green7',
      success8: '$green8',
      success9: '$green9',
      success10: '$green10',
      success11: '$green11',
      success12: '$green12',

      hiContrast: '$slate12',
      loContrast: '$slate11',

      black: '$blackA12',
      white: '$whiteA12',
    },
    space: {
      0: 0,
      1: '4px',
      2: '8px',
      3: '16px',
      4: '24px',
      5: '32px',
      6: '48px',
      7: '64px',
      8: '80px',
      9: '96px',
    },
    sizes: {
      0: 0,
      1: '4px',
      2: '8px',
      3: '16px',
      4: '24px',
      5: '32px',
      6: '48px',
      7: '64px',
      8: '80px',
      9: '96px',
      full: '100%',
      vh: '100vh',
      vw: '100vw',
      bp1: SCREENS[1],
      bp2: SCREENS[2],
      bp3: SCREENS[3],
      bp4: SCREENS[4],
      bp5: SCREENS[5],
    },
    fontSizes: {
      1: '13px',
      2: '15px',
      3: '17px',
      4: '21px',
      5: '27px',
      6: '35px',
      7: '59px',
      8: '72px',
      9: '96px',
    },
    fonts: {
      untitled: 'Untitled Sans, -apple-system, system-ui, sans-serif',
      mono: 'Söhne Mono, menlo, monospace',
    },
    fontWeights: {
      1: 400,
      2: 700,
      3: 900,
    },
    lineHeights: {
      1: 1,
      2: 1.25,
      3: 1.625,
    },
    letterSpacings: {},
    borderWidths: {},
    borderStyles: {},
    radii: {
      1: '4px',
      2: '6px',
      3: '8px',
      4: '12px',
      5: '9999px',
    },
    shadows: {
      1: '0 0 4px rgba(0, 0, 0, .125)',
      2: '0 0 8px rgba(0, 0, 0, .125)',
      3: '0 0 16px rgba(0, 0, 0, .125)',
    },
    zIndices: {
      1: '100',
      2: '200',
      3: '300',
      4: '400',
      5: '999',
    },
    transitions: {},
  },
  media: {
    bp1: `(min-width: ${SCREENS[1]})`,
    bp2: `(min-width: ${SCREENS[2]})`,
    bp3: `(min-width: ${SCREENS[3]})`,
    bp4: `(min-width: ${SCREENS[4]})`,
    bp5: `(min-width: ${SCREENS[5]})`,
  },
  utils: {
    bg: (value: Stitches.PropertyValue<'backgroundColor'>) => ({
      backgroundColor: value,
    }),
    p: (value: Stitches.PropertyValue<'padding'>) => ({
      padding: value,
    }),
    pt: (value: Stitches.PropertyValue<'paddingTop'>) => ({
      paddingTop: value,
    }),
    pr: (value: Stitches.PropertyValue<'paddingRight'>) => ({
      paddingRight: value,
    }),
    pb: (value: Stitches.PropertyValue<'paddingBottom'>) => ({
      paddingBottom: value,
    }),
    pl: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
      paddingLeft: value,
    }),
    px: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: Stitches.PropertyValue<'paddingTop'>) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    m: (value: Stitches.PropertyValue<'margin'>) => ({
      margin: value,
    }),
    mt: (value: Stitches.PropertyValue<'marginTop'>) => ({
      marginTop: value,
    }),
    mr: (value: Stitches.PropertyValue<'marginRight'>) => ({
      marginRight: value,
    }),
    mb: (value: Stitches.PropertyValue<'marginBottom'>) => ({
      marginBottom: value,
    }),
    ml: (value: Stitches.PropertyValue<'marginLeft'>) => ({
      marginLeft: value,
    }),
    mx: (value: Stitches.PropertyValue<'marginLeft'>) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: Stitches.PropertyValue<'marginTop'>) => ({
      marginTop: value,
      marginBottom: value,
    }),
    square: (value: Stitches.PropertyValue<'height'>) => ({
      height: value,
      width: value,
    }),
  },
});

export const darkTheme = createTheme('dark-theme', {
  colors: {
    ...Radix.grayDark,
    ...Radix.mauveDark,
    ...Radix.slateDark,
    ...Radix.sageDark,
    ...Radix.oliveDark,
    ...Radix.sandDark,
    ...Radix.tomatoDark,
    ...Radix.redDark,
    ...Radix.crimsonDark,
    ...Radix.pinkDark,
    ...Radix.plumDark,
    ...Radix.purpleDark,
    ...Radix.violetDark,
    ...Radix.indigoDark,
    ...Radix.blueDark,
    ...Radix.cyanDark,
    ...Radix.tealDark,
    ...Radix.greenDark,
    ...Radix.grassDark,
    ...Radix.orangeDark,
    ...Radix.brownDark,
    ...Radix.skyDark,
    ...Radix.mintDark,
    ...Radix.limeDark,
    ...Radix.yellowDark,
    ...Radix.amberDark,
    ...Radix.blackA,
    ...Radix.whiteA,

    bg1: '$slate1',
    bg2: '$slate2',
    bg3: '$slate3',
    bg4: '$slate4',
    bg5: '$slate5',
    bg6: '$slate6',
    bg7: '$slate7',
    bg8: '$slate8',
    bg9: '$slate9',
    bg10: '$slate10',
    bg11: '$slate11',
    bg12: '$slate12',

    primary1: '$blue1',
    primary2: '$blue2',
    primary3: '$blue3',
    primary4: '$blue4',
    primary5: '$blue5',
    primary6: '$blue6',
    primary7: '$blue7',
    primary8: '$blue8',
    primary9: '$blue9',
    primary10: '$blue10',
    primary11: '$blue11',
    primary12: '$blue12',

    secondary1: '$pink1',
    secondary2: '$pink2',
    secondary3: '$pink3',
    secondary4: '$pink4',
    secondary5: '$pink5',
    secondary6: '$pink6',
    secondary7: '$pink7',
    secondary8: '$pink8',
    secondary9: '$pink9',
    secondary10: '$pink10',
    secondary11: '$pink11',
    secondary12: '$pink12',

    accent1: '$violet1',
    accent2: '$violet2',
    accent3: '$violet3',
    accent4: '$violet4',
    accent5: '$violet5',
    accent6: '$violet6',
    accent7: '$violet7',
    accent8: '$violet8',
    accent9: '$violet9',
    accent10: '$violet10',
    accent11: '$violet11',
    accent12: '$violet12',

    error1: '$red1',
    error2: '$red2',
    error3: '$red3',
    error4: '$red4',
    error5: '$red5',
    error6: '$red6',
    error7: '$red7',
    error8: '$red8',
    error9: '$red9',
    error10: '$red10',
    error11: '$red11',
    error12: '$red12',

    warning1: '$yellow1',
    warning2: '$yellow2',
    warning3: '$yellow3',
    warning4: '$yellow4',
    warning5: '$yellow5',
    warning6: '$yellow6',
    warning7: '$yellow7',
    warning8: '$yellow8',
    warning9: '$yellow9',
    warning10: '$yellow10',
    warning11: '$yellow11',
    warning12: '$yellow12',

    success1: '$green1',
    success2: '$green2',
    success3: '$green3',
    success4: '$green4',
    success5: '$green5',
    success6: '$green6',
    success7: '$green7',
    success8: '$green8',
    success9: '$green9',
    success10: '$green10',
    success11: '$green11',
    success12: '$green12',

    hiContrast: '$slate12',
    loContrast: '$slate11',

    black: '$blackA12',
    white: '$whiteA12',
  },
});
